'use client'

import { useState } from "react";
import { ToolLayout } from "@/components/layouts/ToolLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import { GitBranch, Download, Copy, RefreshCw } from "lucide-react";
import { toast } from "sonner";

interface TemplateItem {
  id: string;
  label: string;
  description: string;
  content: string;
}

const templates: TemplateItem[] = [
  {
    id: "node",
    label: "Node.js",
    description: "JavaScript runtime and npm packages",
    content: `# Dependencies
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Production
build/
dist/

# Environment variables
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Logs
logs
*.log

# Runtime data
pids
*.pid
*.seed

# Coverage directory
coverage/

# ESLint cache
.eslintcache

# Optional npm cache directory
.npm`
  },
  {
    id: "python",
    label: "Python",
    description: "Python applications and packages",
    content: `# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# PyInstaller
*.manifest
*.spec

# Unit test / coverage reports
htmlcov/
.coverage
.pytest_cache/

# Environments
.env
.venv
env/
venv/
ENV/
env.bak/
venv.bak/

# Spyder project settings
.spyderproject
.spyproject`
  },
  {
    id: "java",
    label: "Java",
    description: "Java applications and Maven/Gradle projects",
    content: `# Compiled class files
*.class

# Log files
*.log

# Package Files
*.jar
*.war
*.nar
*.ear
*.zip
*.tar.gz
*.rar

# Maven
target/
pom.xml.tag
pom.xml.releaseBackup
pom.xml.versionsBackup

# Gradle
.gradle
build/
!gradle/wrapper/gradle-wrapper.jar

# IDE
.idea/
*.iws
*.iml
*.ipr
.vscode/`
  },
  {
    id: "react",
    label: "React",
    description: "React.js applications",
    content: `# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# production
/build

# misc
.DS_Store
.env.local
.env.development.local
.env.test.local
.env.production.local

npm-debug.log*
yarn-debug.log*
yarn-error.log*`
  },
  {
    id: "macos",
    label: "macOS",
    description: "macOS system files",
    content: `# General
.DS_Store
.AppleDouble
.LSOverride

# Icon must end with two \r
Icon

# Thumbnails
._*

# Files that might appear in the root of a volume
.DocumentRevisions-V100
.fseventsd
.Spotlight-V100
.TemporaryItems
.Trashes
.VolumeIcon.icns`
  },
  {
    id: "windows",
    label: "Windows",
    description: "Windows system files",
    content: `# Windows thumbnail cache files
Thumbs.db
ehthumbs.db
ehthumbs_vista.db

# Dump file
*.stackdump

# Folder config file
[Dd]esktop.ini

# Recycle Bin used on file shares
$RECYCLE.BIN/

# Windows Installer files
*.cab
*.msi
*.msix
*.msm
*.msp

# Windows shortcuts
*.lnk`
  }
];

export function GitignoreGeneratorClient() {
  const [selectedTemplates, setSelectedTemplates] = useState<string[]>([]);
  const [customContent, setCustomContent] = useState("");
  const [generatedContent, setGeneratedContent] = useState("");

  const handleTemplateToggle = (templateId: string, checked: boolean) => {
    if (checked) {
      setSelectedTemplates(prev => [...prev, templateId]);
    } else {
      setSelectedTemplates(prev => prev.filter(id => id !== templateId));
    }
  };

  const generateGitignore = () => {
    const selectedTemplateContent = selectedTemplates
      .map(id => {
        const template = templates.find(t => t.id === id);
        if (template) {
          return `# ${template.label}\n${template.content}`;
        }
        return '';
      })
      .filter(Boolean)
      .join('\n\n');

    let content = selectedTemplateContent;
    
    if (customContent.trim()) {
      if (content) {
        content += '\n\n# Custom Rules\n' + customContent.trim();
      } else {
        content = '# Custom Rules\n' + customContent.trim();
      }
    }

    if (!content) {
      toast.error("Please select at least one template or add custom content");
      return;
    }

    const header = `# Generated by AZ Tools Gitignore Generator
# Edit this file as needed for your project

`;

    setGeneratedContent(header + content);
    toast.success("Gitignore file generated successfully");
  };

  const handleCopy = () => {
    if (generatedContent) {
      navigator.clipboard.writeText(generatedContent);
      toast.success("Gitignore content copied to clipboard");
    }
  };

  const handleDownload = () => {
    if (generatedContent) {
      const blob = new Blob([generatedContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = '.gitignore';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      toast.success(".gitignore file downloaded");
    }
  };

  const clearAll = () => {
    setSelectedTemplates([]);
    setCustomContent("");
    setGeneratedContent("");
  };

  return (
    <ToolLayout toolId="gitignore-generator" categoryId="developer-tools">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Template Selection */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <GitBranch className="h-5 w-5" />
              Gitignore Generator
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            {/* Template Selection */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <Label>Select Templates</Label>
                {selectedTemplates.length > 0 && (
                  <Badge variant="secondary">
                    {selectedTemplates.length} selected
                  </Badge>
                )}
              </div>
              <div className="space-y-2 max-h-96 overflow-y-auto border rounded-lg p-2">
                {templates.map((template) => (
                  <div key={template.id} className="flex items-start space-x-3 p-2 hover:bg-muted/50 rounded-lg">
                    <Checkbox
                      id={template.id}
                      checked={selectedTemplates.includes(template.id)}
                      onCheckedChange={(checked) => 
                        handleTemplateToggle(template.id, checked as boolean)
                      }
                    />
                    <div className="flex-1 min-w-0">
                      <Label 
                        htmlFor={template.id} 
                        className="text-sm font-medium cursor-pointer"
                      >
                        {template.label}
                      </Label>
                      <p className="text-xs text-muted-foreground">
                        {template.description}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Custom Content */}
            <div className="space-y-2">
              <Label htmlFor="custom-content">Custom Rules (Optional)</Label>
              <Textarea
                id="custom-content"
                value={customContent}
                onChange={(e) => setCustomContent(e.target.value)}
                placeholder="Add your own gitignore rules here..."
                className="min-h-[120px] font-mono text-sm"
              />
              <p className="text-xs text-muted-foreground">
                Add any custom files, folders, or patterns you want to ignore.
              </p>
            </div>

            {/* Actions */}
            <div className="flex flex-wrap gap-2">
              <Button 
                onClick={generateGitignore} 
                className="flex-1 sm:flex-none"
                disabled={selectedTemplates.length === 0 && !customContent.trim()}
              >
                Generate .gitignore
              </Button>
              <Button variant="outline" onClick={clearAll}>
                <RefreshCw className="h-4 w-4 mr-2" />
                Clear All
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* Generated Output */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center justify-between">
              Generated .gitignore File
              {generatedContent && (
                <div className="flex gap-2">
                  <Button size="sm" variant="outline" onClick={handleCopy}>
                    <Copy className="h-4 w-4 mr-1" />
                    Copy
                  </Button>
                  <Button size="sm" variant="outline" onClick={handleDownload}>
                    <Download className="h-4 w-4 mr-1" />
                    Download
                  </Button>
                </div>
              )}
            </CardTitle>
          </CardHeader>
          <CardContent>
            {generatedContent ? (
              <div className="space-y-4">
                <div className="flex items-center gap-2">
                  <Badge variant="secondary">
                    {generatedContent.split('\n').length} lines
                  </Badge>
                  <Badge variant="outline">
                    {Math.round(generatedContent.length / 1024 * 100) / 100} KB
                  </Badge>
                </div>
                <Textarea
                  value={generatedContent}
                  readOnly
                  className="min-h-[400px] font-mono text-sm"
                />
              </div>
            ) : (
              <div className="text-center py-12 text-muted-foreground">
                <GitBranch className="h-12 w-12 mx-auto mb-4 opacity-50" />
                <p className="text-lg mb-2">No .gitignore generated yet</p>
                <p className="text-sm">
                  Select templates or add custom rules, then click Generate
                </p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>

    </ToolLayout>
  );
}